server:
  port: 9030

spring:
  #----------- DB -----------------
  datasource:
    # -- SQL Server
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    url: jdbc:sqlserver://127.0.0.1:1433;databaseName=CRM
    username: sa
    password: dxf...dxf

    # -- MySql
    #driver-class-name: com.mysql.cj.jdbc.Driver
    #url: jdbc:mysql://localhost:3307/demo?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=GMT%2B8
    #username: root
    #password: dxf...dxf

    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      initial-size: 5
      min-idle: 5
      max-active: 20
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000

#----------- mybatis -------------
mybatis-plus:
  #指定mybatis映射文件的地址 【**任意多级目录、 *多个任意字符】
  mapper-locations: classpath:mapper/*.xml
  configuration:
    # 是否开启自动驼峰命名规则映射:从数据库列名到Java属性驼峰命名的类似映射
    map-underscore-to-camel-case: true
    # 如果查询结果中包含空值的列，则 MyBatis 在映射的时候，不会映射这个字段
    call-setters-on-nulls: true

#----------- 阿里大鱼 -------------
aliyun:
  access-key-id: r
  access-key-secret: e
  # 签名
  sign-name: 零悦mall
  # 验证码模板
  code-templateI-id: SMS_182674403
  # 短信通知模板
  message-template-id: SMS_182679347
