server:
  port: 9000

spring:
  #----------- DB -----------------
  datasource:
    # -- SQL Server
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    url: jdbc:sqlserver://47.112.119.181:1433;databaseName=crm
    username: sa
    password: lingyue_2020

    # -- MySql
    #driver-class-name: com.mysql.cj.jdbc.Driver
    #url: jdbc:mysql://localhost:3307/demo?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=GMT%2B8
    #username: root
    #password: dxf...dxf

    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      initial-size: 20
      min-idle: 20
      max-active: 50
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
  #----------- redis --------------
  redis:
    host: 127.0.0.1
    port: 6379
    #cluster:
    #  nodes:
    #    - 127.0.0.1:7010
    #    - 127.0.0.1:7011
    #    - 127.0.0.1:7020
    #    - 127.0.0.1:7021
    #    - 127.0.0.1:7030
    #    - 127.0.0.1:7031
    database: 0
    #password: dxf123dxf
    timeout: 12000 #连接超时时间（毫秒）
    # lettuce连接池
    lettuce:
      pool:
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1
        # 连接池最大连接数（使用负值表示没有限制）
        max-active: 300
        # 连接池中的最大空闲连接
        max-idle: 100
        # 连接池中的最小空闲连接
        min-idle: 20


  #----------- Elasticsearch --------------
  elasticsearch:
    rest:
      uris: http://127.0.0.1:9200
      #read-timeout: "10s"
      #username: "user"
      #password: "secret"


#----------- mybatis -------------
mybatis-plus:
  #指定mybatis映射文件的地址 【**任意多级目录、 *多个任意字符】
  mapper-locations: classpath:mapper/**/*.xml
  configuration:
    # 是否开启自动驼峰命名规则映射:从数据库列名到Java属性驼峰命名的类似映射
    map-underscore-to-camel-case: true
    # 如果查询结果中包含空值的列，则 MyBatis 在映射的时候，不会映射这个字段
    call-setters-on-nulls: true
    # 开启sql日志
    #log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

# ----------- rocketmq ------------
rocketmq:
  # name server 连接地址
  namesrv_addr: 127.0.0.1:9876
  # 消息最大长度 默认1024*4(4M)    ps: 批量发送消息大小超过4M可以通过此配置
  max_message_size: 4096
  #发送消息超时时间,默认3s
  send_msg_timeout: 4000
  # 在同步模式下,发送失败最大重试次数, 默认2次
  retry_times_when_send_failed: 2
  # 在异步模式下,发送失败最大重试次数, 默认2次
  retry_times_when_send_async_failed: 2


# ----------- 自定义 -------------
sys:
  # 域名
  domain-name: http://47.112.119.181/
  # 公众号相对路径拼接成绝对路径
  absolute-path: https://zysy.injoy-mall.cn/obpm/pay/?weixinId=35002#
  # 文件上传路径
  upload-path: D:\uploadField\



# ----------- MinIO文件系统  --------------
minio:
  endpoint: http://47.112.119.181
  port: 9000
  accessKey: minioadmin
  secretKey: minioadmin
  secure: false
